/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/
(function ($, Drupal, drupalSettings) {
  $(document).ready(function () {
    $.ajax({
      type: 'POST',
      cache: false,
      url: drupalSettings.asocol_statistics.url,
      data: drupalSettings.asocol_statistics.data
    });
  });
})(jQuery, Drupal, drupalSettings);
